2022-06-20 20:35:00,044 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-06-20 20:35:00,045 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /home/mahdi/.local/lib/python3.10/site-packages/instabot/bot/bot.py
2022-06-20 20:35:00,046 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-06-20 20:38:18,071 - instabot version: 0.117.0 (api) - WARNING - ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-06-20 20:45:40,441 - instabot version: 0.117.0 (api) - WARNING - ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-06-20 20:46:31,617 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-06-20 20:46:32,239 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2022-06-20 20:46:32,239 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-06-20 20:46:32,239 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-06-20 20:46:32,239 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
